project_id = "bnqynvzwshznmpjetjhz"

[functions.create-admin]
verify_jwt = false

[functions.send-booking-email]
verify_jwt = false

[functions.generate-invoice-pdf]
verify_jwt = false

[functions.send-invoice-email]
verify_jwt = false
